# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Electron build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm install
    - name: Build electron for linux
      if: matrix.os == "ubuntu-latest"
      run: npm run build:linux
    - name: Build electron for macos
      if: matrix.os == "macos-latest"
      run: npm run build:mac
    - name: Build electron for windows
      if: matrix.os == "windows-latest"
      run: npm run build:win
    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: todo_list_1.0.0_amd64.deb
        path: dist/todo_list_1.0.0_amd64.deb
    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: todo_list_1.0.0_amd64.snap
        path: dist/todo_list_1.0.0_amd64.snap
